services:
  world-management-api:
    image: world-management-api
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5053:80"
    depends_on:
      - mssql-graph-db

  mssql-graph-db:
    image: mssql-graph-db
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 5433:1433
    environment:
      - SA_PASSWORD=Yukon900
      - ACCEPT_EULA=Y
