version: "3.9"

services:
  world-management-db:
    container_name: world-management-db
    image: mssql-graph-db
    build:
      context: ../Database
      dockerfile: Dockerfile
    ports:
      - 5433:1433
    environment:
      - SA_PASSWORD=Yukon900
      - ACCEPT_EULA=Y

networks:
  default:
    # use the default network of the karma container
    external: true
    name: karma_docker_api_default